### ISSUE TITLE
Container needs restart for loading theme via URL

### ISSUE THREAD

**Issue by astehlik** [Intera/docker-jquery-ui#1]
Currently the loading of the theme only works once for a started container.

The second time the colors in the preview are correct but the form values in the Theme Roller are not updated.

After restarting the container the form values are filled correctly once.

**Comment by astehlik** [comment]
Update: it's not clear when the problem occurs.

With some clients it seems to work just fine without the restart of the container.

**Comment by gbjbaanb** [comment]
I tried installing docker on my Windows box and it broke things so badly. I'm not going anywhere that again. 

I'm not sure this is that big an issue, as the themes can be set afterwards, download them all and use the stylesheet you want, the biggest issue is getting the js (ie the dependancies for each component) downloaded. 

The problem could be caching - try using it, but turn the cache off in your browser using the web dev tooling.

**Comment by astehlik** [comment]
@gbjbaanb Thanks for your comment.

The issue really seems to be related to browser caching. After clearing everything multiple times it eventually worked.

I started a public instance now of the container: https://jquery-ui.intera.ws/
