### ISSUE TITLE
Does not work for 1.11.4 version with custom theme

### ISSUE THREAD

**Issue by Erika31** [Intera/docker-jquery-ui#2]
Installed docker image without any problem.

But :

Downloading a custom 1.11.4 theme does not work (infinite request or reset connection).
However, downloading a custom 1.12.1 theme DOES work.

The problem is that I can't use the 1.12.1 version, so I need the 1.11.4 one.

Any idea ?

**Comment by astehlik** [comment]
Thanks for the report.

It does indeed seem to work for all versions except 1.11.4 :confused: 

I'll look into it...

**Comment by astehlik** [comment]
Luckily it was the same problem as for the 1.10 builder.

I patched it and pushed new versions for the 1.12.1 and latest tags.

**Comment by Erika31** [comment]
Thanks a lot. It works like a charm !
